json.id reading.id
json.title reading.title
json.author reading.author
json.reading_date reading.reading_date
json.media_type reading.media_type
json.url reading.url
json.text reading.text
json.created_at reading.created_at
json.updated_at reading.updated_at
json.friendly_created_at reading.friendly_created_at