json.id publication.id
json.title publication.title
json.media_type publication.media_type
json.short_blurb publication.short_blurb
json.long_blurb publication.long_blurb
json.pub_date publication.pub_date
json.full_text publication.full_text
json.url publication.url
json.created_at publication.created_at
json.updated_at publication.updated_at